[package]
name = "ancestry_graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.2"
nohash = "0.2.0"

[dev-dependencies]
proptest = "1.2.0"
rand = "0.8.5"
